name:                advent-of-code-y2023-haskell
version:             2023.0
github:              "DCPagan/advent-of-code-2023-haskell"
license:             BSD3
author:              "D.C. Pagan"
maintainer:          "dcpagan@posteo.net"
copyright:           "2023 D.C. Pagan"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         A template for Advent of Code projects in Haskell

dependencies:
- ansi-terminal
- attoparsec
- base >= 4.7 && < 5
- containers
- directory
- lens
- mtl
- optparse-applicative
- parsec
- parser-combinators
- text
- time
- vector

library:
  source-dirs: src
  default-extensions:
    - LambdaCase
    - MultiWayIf
    - RecordWildCards
    - OverloadedStrings
    - GADTs
    - GHC2021

executables:
  advent-of-code-y2023-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N4
    - -with-rtsopts=-qa
    - -with-rtsopts=-C0
    - -funfolding-use-threshold=16
    - -fexcess-precision
    - -optc-O3
    - -optc-ffast-math
    - -O2
    default-extensions:
    - LambdaCase
    - MultiWayIf
    - RecordWildCards
    - OverloadedStrings
    - GADTs
    - GHC2021
    dependencies:
    - advent-of-code-y2023-haskell
